name: QA-Deploy

on:
  push:
    branches:
    - staging

jobs:
  qabuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16.13.2
      uses: actions/setup-node@v1
      with:
        node-version: 16.13.2
    - name: npm install
      run: npm install
    - name: npm run build
      run: npm run build
      env:
        NODE_OPTIONS: --max_old_space_size=8192
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting:admincms-hfn-qa
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_QA }}
        REACT_APP_FIREBASE_AUTH_CONFIG: ${{ secrets.REACT_APP_FIREBASE_AUTH_CONFIG }}
        REACT_APP_MYSRCM_CONFIG: ${{ secrets.REACT_APP_MYSRCM_CONFIG }}
        PROJECT_ID: unifiedplatform-qa